/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frame;
import model.Account;
//import modelmethod.Accountmethod;
import SQLConnect.SQLConnection;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import hdrestaurant.SharedData;
/**
 *
 * @author ASUS OS
 */
public class LoginFr extends javax.swing.JFrame {

    /**
     * Creates new form LoginFr
     */
    public LoginFr() {
        initComponents();
        
        pack();
        setLocationRelativeTo(null);
        setVisible(true);
        
    }
    private void login (){
        try {
            CallableStatement cStmt = null;
            Connection conn = SQLConnection.getConnection();
            String username = txtUsername.getText();
            String password = txtPassword.getText();
            
            cStmt = conn.prepareCall("select account_get_valid(?,?) as isValid");
            cStmt.setString(1,username);
            cStmt.setString(2,password);
            ResultSet rs = cStmt.executeQuery();
            
            /*Accountmethod accmth = new Accountmethod();
        
            Account acc = accmth.checkLogin(username, password);
            SharedData.Account_log = acc;*/
            Account acc = new Account().checkLogin(username, password);
            //Account acc2 = acc.checkLogin(username, password);
            SharedData.Account_log = acc;
            /*if (acc == null){
                JOptionPane.showMessageDialog(this,"Username and Password is wrong. Please try again");
            }else {
                SharedData.Account_log = acc;
                if (rs.next()){
                switch (rs.getInt("isValid")) {
                    case 1:
                        dispose();
                        AdminHomeFr ahome = new AdminHomeFr();
                        ahome.show();
                        break;
                    case 2:
                        dispose();
                        StaffHomeFr shome = new StaffHomeFr();
                        shome.show();
                        break;
                }
            }
            }*/
            if (rs.next()){
                
                switch (rs.getInt("isValid")) {
                    case 1:
                        dispose();
                        /*AdminHomeFr ahome = new AdminHomeFr();
                        ahome.show();*/
                        HomeAdminFr ahome = new HomeAdminFr();
                        ahome.show();
                        break;
                    case 2:
                        dispose();
                        /*StaffHomeFr shome = new StaffHomeFr();
                        shome.show();*/
                        HomeStaffFr shome = new HomeStaffFr();
                        shome.show();
                        break;
                    case -1:
                        JOptionPane.showMessageDialog(this,"Username or Password is wrong. Please try again");
                        txtUsername.setText(username);
                        txtPassword.setText("");
                        break;
                }
            }
            
            //conn.close();
            
        }catch (Exception e) {
            System.out.println("Lỗi: "+e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        welcome = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        usericon = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        passwordicon = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btLogin = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        jButtonHomeCustomer = new javax.swing.JButton();
        jCheckBoxShowPasswd = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Restaurant Management");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);

        Background.setBackground(new java.awt.Color(0, 153, 153));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        welcome.setBackground(new java.awt.Color(255, 255, 255));
        welcome.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        welcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcome.setText("Restaurant Management");
        jPanel1.add(welcome);
        welcome.setBounds(0, 30, 380, 45);

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Sunflower-icon.png"))); // NOI18N
        jPanel1.add(logo);
        logo.setBounds(0, 20, 380, 50);

        usericon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usericon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/loguser.png"))); // NOI18N
        jPanel1.add(usericon);
        usericon.setBounds(30, 70, 52, 52);

        txtUsername.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(txtUsername);
        txtUsername.setBounds(90, 80, 249, 29);

        passwordicon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        passwordicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logkey.png"))); // NOI18N
        jPanel1.add(passwordicon);
        passwordicon.setBounds(30, 120, 52, 52);

        txtPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(txtPassword);
        txtPassword.setBounds(90, 130, 249, 28);

        btLogin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btLogin.setForeground(new java.awt.Color(0, 255, 0));
        btLogin.setText("LOG IN");
        btLogin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btLogin);
        btLogin.setBounds(40, 190, 81, 29);

        btnClose.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnClose.setForeground(new java.awt.Color(255, 0, 0));
        btnClose.setText("CLOSE");
        btnClose.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        jPanel1.add(btnClose);
        btnClose.setBounds(260, 190, 81, 29);

        jButtonHomeCustomer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonHomeCustomer.setText("Customer");
        jButtonHomeCustomer.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonHomeCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHomeCustomerActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonHomeCustomer);
        jButtonHomeCustomer.setBounds(140, 190, 100, 30);

        jCheckBoxShowPasswd.setText("Show password");
        jCheckBoxShowPasswd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxShowPasswdActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBoxShowPasswd);
        jCheckBoxShowPasswd.setBounds(90, 160, 120, 23);

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BackgroundLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 275, Short.MAX_VALUE)
            .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                    .addContainerGap(25, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLoginActionPerformed
        // TODO add your handling code here:
        login();
    }//GEN-LAST:event_btLoginActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void jButtonHomeCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHomeCustomerActionPerformed
        // TODO add your handling code here:
        HomeCustomerFr chome = new HomeCustomerFr();
        chome.show();
    }//GEN-LAST:event_jButtonHomeCustomerActionPerformed

    private void jCheckBoxShowPasswdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxShowPasswdActionPerformed
        // TODO add your handling code here:
        if(jCheckBoxShowPasswd.isSelected()){
            txtPassword.setEchoChar((char)0);
        }else{
            txtPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBoxShowPasswdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFr().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JButton btLogin;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton jButtonHomeCustomer;
    private javax.swing.JCheckBox jCheckBoxShowPasswd;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel passwordicon;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JLabel usericon;
    private javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables
}
